source 'https://rubygems.org'
ruby '2.3.1'

gem 'dalli', '~> 2.7.6'
gem 'recursive-open-struct', '~> 1.0.1'
gem 'foreman', '~> 0.82.0'
gem 'haml', '~> 4.0.7'
gem 'json', '~> 1.8.3'
gem 'rack-cache', '~> 1.6.1'
gem 'rack-contrib', '~> 1.4.0'
gem 'rrd-ffi', '~> 0.2.14'

gem 'sinatra', '~> 1.4.7', :require => 'sinatra/base'
gem 'sinatra-flash', '~> 0.3.0'
gem 'sinatra-param', '~> 1.4.0'
gem 'sinatra-partial', '~> 0.4.0'
gem 'sinatra-json', '~> 0.1.0'
gem 'sinatra-contrib', '~> 1.4.7'

gem 'unicorn'