graph:
  height: 450
  width: 950
  watermark: 'Copyright Obscured (http://www.obscured.se) Sweden.'
  offsets:
    hourly:
      offset: 60.minutes
      step: 1.minute
    daily:
      offset: 24.hours
      step: 1.minute
    weekly:
      offset: 12000.minutes
      step: 5.minute
    monthly:
      offset: 800.hours
      step: 1.hour
    yearly:
      offset: 400.days
      step: 1.hour
    decade:
      offset: 125.months
      step: 24.hours
rrd:
  supported:
    - :cpu
    - :disk
    - :memory
    - :traffic
    - :packages
    - :temperature
    - :uptime
    - :load
  conventions:
   - convention: '%{name}.%{type}.rrd'
   - convention: '%{name}_%{type}.rrd'
metrics:
  typess:
    - type: :cpu
      title: 'CPU Utilization (%{suffix})'
      suffix: '%'
    - type: :disk
      title: 'Disk Usage (%{suffix})'
      suffix: 'B'
    - type: :memory
      title: 'Memory Usage (%{suffix})'
      suffix: 'B'
    - type: :traffic
      title: 'Network Traffic (%{suffix})'
      suffix: 'B/s'
    - type: :packages
      title: 'Packages (%{suffix})'
      suffix: 'P/s'
    - type: :temperature
      title: 'Temperature (%{suffix})'
      suffix: '°C'
    - type: :uptime
      title: 'Uptime (%{suffix})'
      suffix: 'days'
    - type: :load
      title: 'Load (%{suffix})'
      suffix: '%'
data:
  root: '/data'
  sources:
    groups:
      - name: 'ore01.obscured.se'
        nodes:
          - name: 'Boromir'
            path: '/boromir'
            type: :switch
            metrics:
              - title: 'Port %{i} (0:%{i}) Traffic (%{suffix})'
                type: :traffic
                files: "boromir.iface_*.rrd"
          - name: 'Core'
            path: '/core'
            type: :switch
            metrics:
              - title: 'Aggregated traffic (%{suffix})'
                type: :traffic
                files: 'aggregate.traffic.rrd'
              - title: 'Core traffic (%{suffix})'
                type: :traffic
                files: 'core.traffic.rrd'
          - name: 'Gimli'
            path: '/gimli'
            type: :router
            metrics:
              - type: :temperature
                files: 'gimli.temperature.rrd'
              - type: :cpu
                files: 'gimli.cpu.rrd'
              - type: :memory
                files: 'gimli.mem.rrd'
              - title: 'Port 1 (0:0)'
                type: :traffic
                files: ['gimli.iface.1.rrd','gimli.iface.2.rrd']
              - title: 'Port 2 (0:1)'
                type: :traffic
                files: 'gimli.iface.2.rrd'
              - title: 'VLAN Traffic (%{suffix})'
                type: :traffic
                aggregated: true
                files: ['gimli.iface.5.rrd','gimli.iface.6.rrd','gimli.iface.7.rrd','gimli.iface.8.rrd','gimli.iface.9.rrd']
              - title: 'VLAN Load (%{suffix})'
                type: :load
                aggregated: true
                files: ['gimli.iface.5.rrd','gimli.iface.6.rrd','gimli.iface.7.rrd','gimli.iface.8.rrd','gimli.iface.9.rrd']
          - name: 'Pippin'
            path: '/pippin'
            type: :server
            metrics:
              - type: :traffic
                files: 'pippin.inet.rrd'
              - type: :disk
                files: 'pippin.disk.rrd'
              - type: :cpu
                files: 'pippin.totalcpu.rrd'
              - type: :memory
                files: 'pippin.mem.rrd'
              - title: 'Disk Idle Time (%{suffix})'
                type: :load
                files: 'pippin.disk.idle.rrd'
              - type: :utime
                files: 'pippin.uptime.rrd'
          - name: 'Samwise'
            path: '/samwise'
            type: :server
            metrics:
              - type: :cpu
                files: 'samwise.cpu.rrd'
              - type: :traffic
                files: 'samwise.inet.rrd'
              - type: :memory
                files: 'samwise.mem.rrd'
              - type: :traffic
                files: 'samwise.trunk.rrd'
              - type: :utime
                files: 'samwise.uptime.rrd'
          - name: 'Sauron'
            path: '/sauron'
            type: :switch
            metrics:
              - title: 'Port %{i} Traffic (%{suffix})'
                type: :traffic
                files: ['sauron.iface.10101.rrd','sauron.iface.10102.rrd','sauron.iface.10103.rrd','sauron.iface.10104.rrd','sauron.iface.10105.rrd','sauron.iface.10106.rrd','sauron.iface.10107.rrd','sauron.iface.10108.rrd','sauron.iface.10109.rrd','sauron.iface.10110.rrd','sauron.iface.10111.rrd','sauron.iface.10112.rrd','sauron.iface.10113.rrd','sauron.iface.10114.rrd','sauron.iface.10115.rrd','sauron.iface.10116.rrd','sauron.iface.10117.rrd','sauron.iface.10118.rrd','sauron.iface.10119.rrd','sauron.iface.10120.rrd']
              - title: 'Port 21 (T:21) Traffic (%{suffix})'
                type: :traffic
                files: 'sauron.iface.10121.rrd'
              - title: 'Port 22 (T:22) Traffic (%{suffix})'
                type: :traffic
                files: 'sauron.iface.10122.rrd'
              - title: 'Port 23 (T:23) Traffic (%{suffix})'
                type: :traffic
                files: 'sauron.iface.10123.rrd'
              - title: 'Port 24 (T:24) Traffic (%{suffix})'
                type: :traffic
                files: 'sauron.iface.10124.rrd'
      - name: 'ore02.obscured.se'
        nodes:
          - name: 'Celeborn'
            path:  '/celeborn'
            type: :router
            metrics:
              - type: :cpu
                files: 'celeborn.cpu.rrd'
              - type: :memory
                files: 'celeborn.mem.rrd'
              - title: 'Port %{i} (T:%{i}) Traffic (%{suffix})'
                type: :traffic
                files: ['celeborn.iface_1.rrd','celeborn.iface_1.rrd']
              - title: 'VLAN 2000 Traffic (%{suffix})'
                type: :traffic
                files: 'celeborn.iface_17.rrd'
              - title: 'VLAN 3000 Traffic (%{suffix})'
                type: :traffic
                files: 'celeborn.iface_18.rrd'
              - title: 'VLAN 3001 Traffic (%{suffix})'
                type: :traffic
                files: 'celeborn.iface_19.rrd'
              - title: 'VLAN 4000 Traffic (%{suffix})'
                type: :traffic
                files: 'celeborn.iface_20.rrd'
              - title: 'VLAN 4001 Traffic (%{suffix})'
                type: :traffic
                files: 'celeborn.iface_21.rrd'
              - title: 'VLAN 4002 Traffic (%{suffix})'
                type: :traffic
                files: 'celeborn.iface_22.rrd'
              - title: 'VLAN 1001 Traffic (%{suffix})'
                type: :traffic
                files: 'celeborn.iface_23.rrd'
              - title: 'VLAN Traffic (%{suffix})'
                type: :traffic
                aggregated: true
                files: ['celeborn.iface_17.rrd','celeborn.iface_18.rrd','celeborn.iface_19.rrd']
              - title: 'VLAN Load (%{suffix})'
                type: :load
                aggregated: true
                files: ['celeborn.iface_17.rrd','celeborn.iface_18.rrd','celeborn.iface_19.rrd']
          - name: 'Legolas'
            path:  '/legolas'
            type: :switch
            metrics:
              - title: 'VLAN 1000 Traffic (%{suffix})'
                type: :traffic
                files: '10.0.0.2_1000.rrd'
              - title: 'VLAN 2000 Traffic (%{suffix})'
                type: :traffic
                files: '10.0.0.2_2000.rrd'
              - title: 'VLAN 3000 Traffic (%{suffix})'
                type: :traffic
                files: '10.0.0.2_3000.rrd'
              - title: 'VLAN 3001 Traffic (%{suffix})'
                type: :traffic
                files: '10.0.0.2_3001.rrd'
              - title: 'VLAN Traffic (%{suffix})'
                type: :traffic
                aggregated: true
                files: ['10.0.0.2_1000.rrd','10.0.0.2_2000.rrd','10.0.0.2_3000.rrd','10.0.0.2_3001.rrd']
              - title: 'VLAN Load (%{suffix})'
                type: :load
                aggregated: true
                files: ['10.0.0.2_1000.rrd','10.0.0.2_2000.rrd','10.0.0.2_3000.rrd','10.0.0.2_3001.rrd']
              - title: 'Port 21 (T:21) Traffic (%{suffix})'
                type: :traffic
                files: '10.0.0.2_10121.rrd'
              - title: 'Port 22 (T:22) Traffic (%{suffix})'
                type: :traffic
                files: '10.0.0.2_10122.rrd'
              - title: 'Port 23 (T:23) Traffic (%{suffix})'
                type: :traffic
                files: '10.0.0.2_10123.rrd'
              - title: 'Port 24 (T:24) Traffic (%{suffix})'
                type: :traffic
                files: '10.0.0.2_10124.rrd'
          - name: 'VM01'
            path: '/vm01'
            type: :server
            metrics:
              - type: :cpu
                files: 'vm01.cpu.rrd'
              - type: :traffic
                files: 'vm01.inet.rrd'
              - type: :memory
                files: 'vm01.mem.rrd'
              - type: :traffic
                files: 'vm01.trunk.rrd'
              - type: :utime
                files: 'vm01.uptime.rrd'
          - name: 'VM02'
            path: '/vm02'
            type: :server
            metrics:
              - type: :cpu
                files: 'vm02.cpu.rrd'
              - type: :traffic
                files: 'vm02.inet.rrd'
              - type: :memory
                files: 'vm02.mem.rrd'
              - type: :traffic
                files: 'vm02.trunk.rrd'
              - type: :utime
                files: 'vm02.uptime.rrd'
          - name: 'VM03'
            path: '/vm03'
            type: :server
            metrics:
              - type: :cpu
                files: 'vm03.cpu.rrd'
              - type: :traffic
                files: 'vm03.inet.rrd'
              - type: :memory
                files: 'vm03.mem.rrd'
              - type: :traffic
                files: 'vm03.trunk.rrd'
              - type: :utime
                files: 'vm03.uptime.rrd'
          - name: 'VM04'
            path: '/vm04'
            type: :server
            metrics:
              - type: :cpu
                files: 'vm04.cpu.rrd'
              - type: :traffic
                files: 'vm04.inet.rrd'
              - type: :memory
                files: 'vm04.mem.rrd'
              - type: :traffic
                files: 'vm04.trunk.rrd'
              - type: :utime
                files: 'vm04.uptime.rrd'
          - name: 'VM05'
            path: '/vm05'
            type: :server
            metrics:
              - type: :cpu
                files: 'vm05.cpu.rrd'
              - type: :traffic
                files: 'vm05.inet.rrd'
              - type: :memory
                files: 'vm05.mem.rrd'
              - type: :traffic
                files: 'vm05.trunk.rrd'
              - type: :utime
                files: 'vm05.uptime.rrd'
      - name: 'ore03.obscured.se'
        nodes:
          - name: 'Eomer'
            path: '/eomer'
            type: :server
            metrics:
              - type: :disk
                files: 'eomer.disk.rrd'
              - type: :traffic
                files: 'eomer.inet.rrd'
              - type: :memory
                files: 'eomer.mem.rrd'
              - type: :cpu
                files: 'eomer.totalcpu.rrd'
              - type: :utime
                files: 'eomer.uptime.rrd'
          - name: 'Galadriel'
            path: '/galadriel'
            type: :server
            metrics:
              - type: :disk
                files: 'eomer.disk.rrd'
              - type: :traffic
                files: 'eomer.inet.rrd'
              - type: :memory
                files: 'eomer.mem.rrd'
              - type: :cpu
                files: 'eomer.totalcpu.rrd'
              - type: :utime
                files: 'eomer.uptime.rrd'